### ISSUE TITLE
Error when addrBuildHashTable is called

### ISSUE THREAD

**Issue by snease** [inincs/pyNCS#28]
I'm working with a real-time AER viewer that calls pyST.STas.addrBuildHashTable(stas). On line 1366, addrPhysicalLogicalDecode(stas, addr_phys) is called. However, addr_phys isn't initialized anywhere. My proposed change:

```
addr_phys = addrLogicalPhysicalDecode(stas, stas.allpos)
addrPhysicalLogicalDecode(stas, addr_phys)
```

This fixes the error for me. I tried to create a branch and push it to the repo so I could make a pull request, but I don't have permission to access the repo.

Best regards,
Steve

**Comment by eneftci** [comment]
Steve,
Are you on the master or development branch?
Emre

**Comment by snease** [comment]
I'm on the development branch. Is the master preferred?

**Comment by eneftci** [comment]
No development is preferred (it will be merged to master soon). Let me take a look.
Emre

**Comment by eneftci** [comment]
The hash table implementation as it is will probably disappear soon because it does not scale well (the table becomes too large for 100k neurons). We will probably add a mask to it so not all addresses are decoded and stored. In the meantime your fix will do.
