### ISSUE TITLE
Please add amwhatley as a collaborator

### ISSUE THREAD

**Issue by amwhatley** [inincs/pyNCS#29]
Hi! I'm finally ready to perform the repository changes we discussed at CapoCaccia last year, i.e. the development branch becomes the new master and so on.

Could you please add me as a collaborator such that I can push to the repository?
Thanks,

Adrian

**Comment by sheiksadique** [comment]
Hi Adrian, that is great!

Looks like you are already a collaborator. So fire away.

Sadique
